num = 1
number = open("page_views.txt", 'r')
a = number.read
count = int(a) + 1
number.seek(0)
number.close()
print()
print("c " + str(count))
print()
number = open("page_views.txt", 'w')
number.write(str(count))
number.close()
number = open("page_views.txt", 'r')
a = number.read()
print()
print(" - " + str(a))
print()
count = int(a) + int(num)
number.seek(0)
number.close()
print()
print("c " + str(count))
print()
number = open("page_views.txt", 'w')
number.write(str(count))
number.close()
